name: hello-world-workflow

on:
  push:
    branches:
      - master
      - main
      - production

jobs:
  hellow_world:
    runs-on: ubuntu-latest
    steps:
      - name: "print hellow world"
        run: echo "hello world ...."
