name: multi event pipeline/workflow                     # name of workflow

on:                                                     # defines events when the workflow will trigger 
  push:                                                 # when code is pushed on defined branches workflow will trigger
    branches:                                           # defines nranches for trigger
      - master                                         
      - test

  pull_request:                                         # workflow will trigger when pull request is made at master
    branches:
      - master

jobs:                                                   # jon section starts here
  on-push:                                              # job name
    if: github.event_name == 'push'                     # runs only on event push
    runs-on: ubuntu-latest                              # specifies os for the job
    steps:                                              # steps section starts here
      - name: "Running on master/test push"             # Step name  (step1)
        run: echo "Running on master/test push"         # Action (Shell command)

  on-pull-request:                                      # job name
    if: github.event_name == 'pull_request'             # runs only on event pull_request
    runs-on: ubuntu-latest                              # specifies os for the job
    steps:
      - name: "running on pull request"                 # step name (step2)
        run: echo "Running on pull request on master"   # Action (shell command)
       